# Generated by Django 2.0.13 on 2019-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.PositiveSmallIntegerField()),
                ('launch_date', models.DateField()),
                ('rocket_name', models.TextField()),
                ('mission_patch_link', models.URLField()),
            ],
        ),
    ]
